config/routes.rb
Reportinator::Rails::Engine.routes.draw do
  resources :reports

  root to: "reports#index"
  
  get "/download", to: "reports#download"
  get "/*id", to: "reports#show"
end

app/models/reportinator/rails/application_record.rb
module Reportinator
  module Rails
    class ApplicationRecord < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end

app/models/reportinator/rails/report.rb
module Reportinator
  module Rails
    class Report < Base
      attribute :template

      def self.list
        templates = config.configured_directories.map do |dir|
          config.configured_suffixes.map { |suffix| Dir["#{dir}/**/*#{suffix}"] }.flatten
        end
        templates = templates.flatten.uniq.map { |template| template_name(template)}
        templates.select { |template| !File.basename(template).start_with? "_" }
      end

      def self.all
        return [] unless list.present?
        list.map { |template| load(template) }
      end

      def self.sort_and_reverse(array)
        raise "Not an array" unless array.instance_of? Array
        array.sort.reverse
      end

      def self.template_name(path)
        directories = sort_and_reverse(config.configured_directories)
        suffixes = sort_and_reverse(config.configured_suffixes)
        directories.each do |directory|
          next unless path.start_with? directory
          path.delete_prefix! directory
          path.delete_prefix! "/"
          break
        end
        suffixes.each do |suffix|
          next unless path.end_with? suffix
          path.delete_suffix! suffix
          path.delete_suffix! "."
          break
        end
        path
      end

      def self.load(template, additional_params = {})
        ReportLoader.load(template, additional_params)
      end
    end
  end
end

app/controllers/reportinator/rails/application_controller.rb
module Reportinator
  module Rails
    class ApplicationController < ActionController::Base
    end
  end
end

app/controllers/reportinator/rails/reports_controller.rb
module Reportinator::Rails
  class ReportsController < ApplicationController
    include Reportinator::Rails::ReportsHelper
    
    before_action :set_report, only: %i[ show ]
    layout config.report_layout

    # GET /reports
    def index
      # @reports = Report.all
    end

    # GET /reports/1
    def show
      @template = params[:id]
      @params = {template: @template}
      if params[:reportinator_report].present?
        @params.merge!({reportinator_report: params.require(:reportinator_report).permit!})
      end
    end

    def download
      variables = get_report_variables(params[:reportinator_report])
      template = params[:template]
      if template.present?
        loader = get_loader(template, variables)
        set_variables(loader)
        data = @report.to_csv
        filename = "#{template.parameterize}-#{Time.now.strftime("%Y%m%d")}.csv"
        send_data(data, filename: filename)
      else
        redirect_to root_path(template), notice: "Missing template"
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_report
        variables = get_report_variables(params[:reportinator_report])
        loader = get_loader(params[:id], variables)
        set_variables(loader)
      rescue => e
        @report = Reportinator::Report.new
        @report.insert(Reportinator::Row.create("Invalid Table: #{e.to_s}"))
      end

      def get_report_variables(inputs)
        return unless inputs.present?
        transform_params(inputs)
      end

      def get_loader(template, variables)
        Reportinator::ReportLoader.load(template, variables: variables)
      end

      def set_variables(loader)
        return false unless loader.instance_of? Reportinator::ReportLoader
        @loader = loader
        @metadata = loader.get_metadata
        @report = loader.report
      end

      # Only allow a list of trusted parameters through.
      def report_params
        params.fetch(:report, {})
      end
  end
end

app/helpers/reportinator/rails/application_helper.rb
module Reportinator
  module Rails
    module ApplicationHelper
    end
  end
end

app/helpers/reportinator/rails/reports_helper.rb
module Reportinator::Rails
  module ReportsHelper

    def transform_params(variables)
      new_variables = {}
      variables.each do |key, value|
        new_variables.merge! transform_variable(key, value)
      end
      new_variables
    end

    def transform_variable(key, value)
      variable = key.to_s
      input_class = Reportinator::Rails::Input.find_input(variable)
      return false unless input_class.present?
      new_value = input_class.new(value: value).transform
      new_key = variable.sub(input_class.prefix, "").to_sym
      {new_key => new_value}
    end
  end
end

app/views/layouts/reportinator/rails/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reportinator rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "reportinator/rails/tailwind", "data-turbo-track": "reload" %>
  </head>
  <body>
    <main class="flex flex-col items-center">
      <div class="max-w-screen-lg w-full p-2">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/partials/_row.html.erb
<tr>
  <% columns.each do |column| %>
    <% if header %>
      <th class="px-4 py-2 border-b border-gray-400 text-start"><%= simple_format(column.output.to_s) %></th>
    <% else %>
      <td class="px-4 py-2 border-b border-gray-300"><%= simple_format(column.output.to_s) %></td>
    <% end %>
  <% end %>
</tr>

app/views/partials/forms/_date.html.erb
<%
  name = id.to_s.titleize
  default_value = default.instance_of?(Time) ? default.strftime("%Y-%m-%d") : default
  value = params.dig(:reportinator_report, "date_#{id}") || default_value
%>

<div>
  <%= form.label "date_#{id}", value: name %>
  <%= form.date_field "date_#{id}", value: value, class: "form-input" %>
</div>

app/views/partials/forms/_number.html.erb
<%
  name = id.to_s.titleize
  value = params.dig(:reportinator_report, "number_#{id}") || default
%>
<div>
  <%= form.label "number_#{id}", value: name %>
  <%= form.number_field "number_#{id}", value: value, class: "form-input" %>
</div>

app/views/partials/forms/_select.html.erb
<%
  name = id.to_s.titleize
  value = params.dig(:reportinator_report, "select_#{id}") || default
%>
<div>
  <%= form.label "select_#{id}", value: name %>
  <%= form.select "select_#{id}", info[:options], { selected: value }, class: "form-input" %>
</div>

app/views/partials/forms/_string.html.erb
<%
  name = id.to_s.titleize
  value = params.dig(:reportinator_report, "string_#{id}") || default
%>
<div>
  <%= form.label "string_#{id}", value: name %>
  <%= form.text_field "string_#{id}", value: value, class: "form-input" %>
</div>

app/views/reportinator/rails/reports/_form.html.erb
<% 
  inputs = @metadata[:inputs]
  type_list = Reportinator::Rails::Input.type_list
%>
<% if inputs.is_a? Hash %>
  <div>
    <%= form_with(scope: report, url: report_path, method: :get, html: { class: "flex gap-2 items-end" }) do |form| %>
      <% inputs.each do |variable, info| %>
        <% type = info[:type] %>
        <% if type_list[type].present? %>
          <% partial = type_list[type]::PARTIAL %>
          <% value = info[:default] %>
          <% if @variables.present? && @variables[variable].present? %>
            <% value = @variables[variable] %>
          <% end %>
          <%= render partial: partial, locals: { form: form, id: variable, default: value, info: info } %>
        <% end %>
      <% end %>
      <div>
        <%= form.submit "Run", class: "form-submit cursor-pointer" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/reportinator/rails/reports/_report.html.erb
<% url = "#{root_path}#{template}" %>
<tr class="hover:bg-gray-100 cursor-pointer" onclick="location.href='<%= url%>';">
  <td class="px-4 py-2 border-b border-gray-300">
    <a href="<%= url %>"><%= template %></a>
  </td>
</tr>

app/views/reportinator/rails/reports/_table.html.erb
<table class="grow">
  <% rows = @report.rows %>
  <% rows.each do |row| %>
    <% header = (row == rows.first) %>
    <%= render partial: "partials/row", locals: { columns: row.columns, header: header } %>
  <% end %>
</table>

app/views/reportinator/rails/reports/edit.html.erb
<h1>Editing report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Show this report", @report %> |
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reportinator/rails/reports/index.html.erb
<div class="flex flex-col w-full items-center justify-center">
  <div class="max-w-screen-lg md:w-full">
    <h1>Reportinator</h1>
    <table class="grow">
      <% Reportinator::Rails::Report.list.each do |template| %>
        <%= render partial: "report", locals: { template: template }%>
      <% end %>
    </table>
  </div>
</div>

app/views/reportinator/rails/reports/new.html.erb
<h1>New report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reportinator/rails/reports/show.html.erb
<div class="flex flex-col w-full items-center justify-center">
  <div>
    <h1>
      <%= link_to "Reportinator", root_path %> > <%= params[:id].titleize %>
    </h1>

    <% if @metadata.present? && @metadata.include?(:inputs) %>
      <%= render partial: "form", locals: { report: @report } %>
    <% end %>

    <% begin %>
      <%= link_to "Download as CSV", download_path(@params) %>
      <%= render partial: "table" %>
    <% rescue %>
      <p>Report Error</p>
    <% end %>
  </div>
</div>